### PR TITLE
Feat/add swagger

### LINKED ISSUE #1322: idea: Cortex API Playground
### Problem Statement

- Users don't know the current API
- It is hard to craft CURL requests from scratch

### Feature Idea

- Bring back the API playground at `localhost:port` eg `http://127.0.0.1:3928/`
- Autogenerated (not manual pls)

### PR DESCRIPTION
**Pull request by nguyenhoangthuan99**
Fix #1322 

Add swagger for api. After running server, go to `http://127.0.0.1:3928/swagger` to access swagger page.

image

### CODE REVIEW

**Comment by dan-menlo** [comment]
For easier discoverability, it possible to put this at the root URL (localhost:3928) vs the /swagger route?

**Comment by nguyenhoangthuan99** [comment]
yes, we can also access to swagger page through `http://localhost:3928/swagger`

**Review by vansangpfiev — APPROVED** [review]

**Comment by gabrielle-ong** [comment]
@nguyenhoangthuan99 
1. I think Daniel is suggesting we post it at the root url `http://localhost:3928`
As a user, from the CLI I wont know to go to `/swagger` 

2. Also requesting - can we add the url to the output of `cortex start`? So its easily opened (like previous cortex.js output)

Current:
```
Host: 127.0.0.1 Port: 3928
Server started
```

Suggested:
```
Server started!
http://127.0.0.1:3928
```

**Comment by gabrielle-ong** [comment]
@nguyenhoangthuan99 
1. I think Daniel is suggesting to use the root url `http://127.0.0.1:3928` (or maybe `/api`?), as a user I may not know to go to /swagger
2. Previous version of cortex.js CLI - `cortex start` outputed this link, so as a user I can easily click and open the link. Can we bring that back? 

Currently:
```
> cortex start
Host: 127.0.0.1 Port: 3928
Server started
```

**Comment by nguyenhoangthuan99** [comment]
I fixed in this pr #1392

**Pull request merged**
