### PR TITLE
feat: add hardware-info binary

### PR DESCRIPTION
**Pull request by vansangpfiev**
## Describe Your Changes

- This is a PR to solve a part of https://github.com/janhq/cortex.cpp/issues/1217. We use `hardware-info` to detect CPU instructions and Nvidia GPU if supported.
Output example:
```
{"os":"windows","arch":"amd64","suitable_avx":"avx2","gpu_info":[{"id":"0","name":"NVIDIA GeForce RTX 3090","arch":"ampere","driver_version":"552.12","cuda_driver_version":"12.4","compute_cap":"8.6"}]}
```

## Fixes Issues

- Closes #
- Closes #

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Review by namchuai — APPROVED** [review]
✅ lgtm

**Comment by dan-menlo** [comment]
@vansangpfiev Can I check, is `hardware-info` we are using https://github.com/lfreist/hwinfo (MIT)?

Or which package are we using and what is its license? (can you link me to the repo?)

**Comment by vansangpfiev** [comment]
> @vansangpfiev Can I check, is `hardware-info` we are using https://github.com/lfreist/hwinfo (MIT)?
> 
> Or which package are we using and what is its license? (can you link me to the repo?)

We build the `hardware-info`, it just another Cmake target located in our examples' folder which use functions that were written by @namchuai.

**Comment by dan-menlo** [comment]
> > @vansangpfiev Can I check, is `hardware-info` we are using https://github.com/lfreist/hwinfo (MIT)?
> > Or which package are we using and what is its license? (can you link me to the repo?)
> 
> We build the `hardware-info`, it just another Cmake target located in our examples' folder which use functions that were written by @namchuai.

Thanks - given that it's MIT licensed, we will not have issues.

**Pull request closed without merging**
