### PR TITLE
chore: update `.cortexrc` fields

### PR DESCRIPTION
**Pull request by namchuai**
## Describe Your Changes

- Update the fields from
`host` -> `apiServerHost`
`port` -> `apiServerPort`
Previously I mistakenly put it as `host` and `port`

## Screenshot
Screenshot 2024-09-09 at 10 18 42

## Fixes Issues
- https://github.com/janhq/cortex.cpp/issues/1031

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Review by vansangpfiev — APPROVED** [review]

**Comment by dan-menlo** [comment]
@namchuai @vansangpfiev Given the amount of port number collisions at 4 digits, should we consider a standard port for Cortex that is higher rank? 

- 267839 = Cortex in T9

Outside of that: how did we choose 3928?

**Review by dan-menlo — APPROVED** [review]
Lgtm

**Comment by dan-menlo** [comment]
@namchuai Out of curiosity, what was the issue with the initial `port` and `host` varnames? 

- I'm not sure if it's an improvement to make it more verbose
- Given that cortex.cpp only has a single port/host now (vs. cortex platform in the original issue)

**Comment by namchuai** [comment]
> @namchuai Out of curiosity, what was the issue with the initial `port` and `host` varnames?
> 
> * I'm not sure if it's an improvement to make it more verbose
> * Given that cortex.cpp only has a single port/host now (vs. cortex platform in the original issue)

One of the reason is I want to make it compatible with what user currently have. Some user already installed cortex (cortexjs) and they already have `.cortexrc`

**Pull request merged**
